services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ./db:/tmp/db
    networks:
      - mongo_network

volumes:
  mongodb_data:

networks:
  mongo_network:
    driver: bridge
