name: Eliminar archivos no deseados

on:
  push:
    branches:
      - '**'
  pull_request_target:

jobs:
  remove_unwanted_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Eliminar carpeta obj
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        UNWANTED_PATH="Backend/HireAProBackend/obj"
        git rm -rf --ignore-unmatch "$UNWANTED_PATH"
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Eliminando carpeta no deseada: $UNWANTED_PATH"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
        else
          echo "No hay cambios para comprometer."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      shell: bash
