name: Eliminar archivos no deseados

on:
  push:
    branches:
      - '**'
  pull_request_target:

jobs:
  remove_unwanted_files:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event_name == 'push' && github.ref || github.event.pull_request.head.ref }}
        repository: ${{ github.event_name == 'push' && github.repository || github.event.pull_request.head.repo.full_name }}
        token: ${{ github.event_name == 'push' && secrets.GITHUB_TOKEN || secrets.PAT_TOKEN }}
    - name: Eliminar carpeta obj
      shell: bash
      env:
        UNWANTED_PATH: 'Backend/HireAProBackend/obj'
      run: |
        set -e  # Opcional: Terminar el script si ocurre un error no controlado

        # Configurar el usuario de Git
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

        # Verificar si la carpeta existe
        if [ -d "$UNWANTED_PATH" ]; then
          echo "La carpeta $UNWANTED_PATH existe. Procediendo a eliminarla."

          # Eliminar la carpeta no deseada
          git rm -rf --ignore-unmatch "$UNWANTED_PATH" || true

          # Confirmar y empujar los cambios si hay modificaciones
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Eliminando carpeta no deseada: $UNWANTED_PATH"
            git push || true
          else
            echo "No hay cambios para comprometer."
          fi
        else
          echo "La carpeta $UNWANTED_PATH no existe. No es necesario eliminar."
        fi

        exit 0  # Aseguramos que el script termine con éxito
